{{- $serverPort  := .Values.server.port -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Release.Namespace }}
data:
  manager.yaml: |+
    address: "0.0.0.0:{{ .Values.manager.port }}"
    all_servers_address:
{{- range $index, $element := .Values.configmap.all_servers }}
      - {{ $element }}:{{ $serverPort }}
{{- end }}
    virtual_nodes:
      {{ .Values.manager.virtual_nodes }}
    log_level:
      {{ .Values.sealfs.logLevel }}
