---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: sealfs.csi.k8s.io
parameters:
  manager-host: "127.0.0.1"
  manager-port: "8081"
reclaimPolicy: Delete
volumeBindingMode: Immediate
